#!/bin/sh
# install.sh — set up HaoudejProgram on a Raspberry Pi (Debian / Raspberry Pi OS).
#
#   sudo ./install.sh
#
# Installs the system packages, including the Python deps (MySQLdb, requests)
# from apt so the system python3 can run main.py, and writes /etc/cron.d/caisse
# to run `main.py --sync` every day at 23:00. No weekly --reconcile job is
# installed.
#
# Safe to re-run: it overwrites the cron file.
set -eu

if [ "$(id -u)" -ne 0 ]; then
    echo "install.sh needs root — re-run with: sudo $0" >&2
    exit 1
fi

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
CRON_FILE=/etc/cron.d/caisse  # cron.d ignores names containing dots
# Owner of the checkout, so config.conf doesn't end up root-owned.
OWNER="$(stat -c %U "$APP_DIR")"

echo "==> Installing system packages"
apt-get update
# python3-mysqldb/python3-requests are the system builds of requirements.txt;
# arp-scan backs the MAC fallback; at/atd run the 30-minute upload retries.
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-mysqldb python3-requests arp-scan at cron

systemctl enable --now atd
systemctl enable --now cron

if [ ! -f "$APP_DIR/config.conf" ]; then
    sudo -u "$OWNER" cp "$APP_DIR/config.conf.example" "$APP_DIR/config.conf"
    chmod 600 "$APP_DIR/config.conf"
    echo "==> Created config.conf from the example — edit it with your DB credentials"
fi

echo "==> Writing $CRON_FILE"
cat > "$CRON_FILE" <<EOF
# HaoudejProgram — daily MySQL sales export and upload.
# Generated by install.sh; re-run it to rewrite this file.
#
# Runs as root: the MAC fallback in [mysql] shells out to arp-scan, which
# needs raw sockets. Output goes to $APP_DIR/logs/YYYY-MM-DD.log.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAILTO=""

# --sync exports TODAY, so this runs in the evening once trading has closed.
# To backfill a missed day, run main.py --date YYYY-MM-DD.
0 23 * * *	root	cd $APP_DIR && python3 main.py --sync
EOF
chmod 644 "$CRON_FILE"  # cron ignores group/other-writable files

echo "==> Done. Cron: every day at 23:00 -> main.py --sync"
echo "    Test it now with: cd $APP_DIR && sudo python3 main.py --sync"
